### ISSUE TITLE
Scroll not smooth in IOS devices

### ISSUE THREAD

**Issue by little-yellow-bean** [bartholomej/ngx-scrolltop#11]
In IOS devices browser, the scroll process is not smooth

**Comment by bartholomej** [comment]
@little-yellow-bean Thank you for your feedback.

You're right. This is because Safari does not support `behaviour: 'smooth'` So I tried to fix it using a custom polyfill.

Of course, I could use some more robust polyfills for animations, but I want to keep ngx-scrolltop clean, small, pure Angular and without any dependencies.

Can you test how it works now?

Try it here: https://ngx-scrolltop.stackblitz.io/
OR
Install beta in your project `yarn add ngx-scrolltop@beta`

Thx!

**Comment by little-yellow-bean** [comment]
> @little-yellow-bean Thank you for your feedback.
> 
> 
> 
> You're right. This is because Safari does not support `behaviour: 'smooth'` So I tried to fix it using a custom polyfill.
> 
> 
> 
> Of course, I could use some more robust polyfills for animations, but I want to keep ngx-scrolltop clean, small, pure Angular and without any dependencies.
> 
> 
> 
> Can you test how it works now?
> 
> 
> 
> Try it here: https://ngx-scrolltop.stackblitz.io/
> 
> OR
> 
> Install beta in your project `yarn add ngx-scrolltop@beta`
> 
> 
> 
> Thx!

Hi,

Thanks for the reply, I have made a test on my IOS device, it seems it still has the problem. I have attached a gif (sorry for the resolution)

![image](https://user-images.githubusercontent.com/28442139/106587944-f4693480-6595-11eb-8f0c-fec591eefd5d.gif)

Cheers

**Comment by vub** [comment]
I face same issue in iOS.

So you can try to use polyfill:
https://www.npmjs.com/package/smoothscroll-polyfill

It's work for me now.

**Comment by bartholomej** [comment]
Hi @little-yellow-bean and @vub 

I just released new beta version. Can you test how it works now?

Install beta (v4.0.0) in your project like this:

```bash
npm install ngx-scrolltop@ios
 ```

**Comment by little-yellow-bean** [comment]
Hi @bartholomej,

I have tested it on iPhone and iPad, it works well!

Thanks.
