### ISSUE TITLE
Not working with Angular 12

### ISSUE THREAD

**Issue by slst19** [bartholomej/ngx-scrolltop#30]
I have tried 

`ng add ngx-scrolltop`

And it was giving error for ng-add support.

So then I installed manually 

`npm install ngx-scrolltop --save`

And then added in app.component.html
`<ngx-scrolltop></ngx-scrolltop>`

and made sure app.module.ts has the NgxScrollTopModule with import.

And I have tried checking in couple of ways and no matter I do after scrolling down nothing shows up.

**Comment by bartholomej** [comment]
Hi @slst19 I will take a look soon.

Meanwhile you can try ng12 (ivy compatible) version
```bash
ng add ngx-scrolltop@ng12
```
or
```bash
npm install ngx-scrolltop@ng12 --save
```

Some ideas:
1. Make sure you put `<ngx-scrolltop></ngx-scrolltop>` in your real root component (in some custom cases it is not called `app.component.html`)
2. Try to find `ngx-scrolltop` in your rendered DOM. It would be overrided with some of your custom styles.

**Comment by bartholomej** [comment]
Angular 13 is here and old libraries are deprecated (without ivy).

Since ngx-scrolltop v3, the library is compiled with IVY and fully supports Angular12+ (you can't use this with older Angular version anymore!)

If you still need to use it with an older version of Angular, then use version 2, which is still available: `ng add ngx-scrolltop@2`

[More info in readme](https://github.com/bartholomej/ngx-scrolltop#compatibility)
