### ISSUE TITLE
Disable scrolltop animation on page navigation?

### ISSUE THREAD

**Issue by dwasyluk** [bartholomej/ngx-scrolltop#42]
Is there a way to disable the scrollTop animation on route changes? I want the page to snap to the top but its animating the scroll to the top which is making for a poor user experience.

**Comment by bartholomej** [comment]
Hi @dwasyluk 
Can you be a little more specific, please?
Do you have an example?

Is it that issue when you press the scrollTop button and change the url during the animation? 
That seems like a very unlikely case to me, because the animation is so fast that you have no chance to click on anything meaningful :)
